# defaults.yaml

# Hydra configuration
defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  job:
    chdir: yes

wandb:
  project: backdoor

device: "cuda:0"
poison:
  target: 8
  portion: 0.02

train:
  num_epochs: 20
  batch_size: 256
  lr: 0.001
